@startuml
'https://plantuml.com/class-diagram
Computer *-- XiJieHardDisk
Computer *-- IntelCPU
Computer *-- KingstonMemory

class Computer {
    - hardDisk: XiJieHardDisk
    - cpu: IntelCPU
    - memory: KingstonMemory
    + setHardDisk(XiJieHardDisk disk): void
    + getHardDisk(): XiJieHardDisk
    + setCpu(IntelCPU cpu): void
    + getCpu(): IntelCPU
    + setMemory(KingstonMemory memory): void
    + getMemory(): KingstonMemory
    + run(): void
}
class XiJieHardDisk {
    + save(String data): void
    + get(): String
}

class IntelCPU {
    + run(): void
}

class KingstonMemory {
    + save(): void
}

@enduml